"use strict";
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const root = path.join(__dirname, '..');
const data = fs.readFileSync(path.join(root, 'data.js'), 'utf8');
const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const recipes = vm.runInNewContext(data.slice(data.indexOf('const RECIPES = ['), data.indexOf('// 💰 FINANCE')) + '\nRECIPES');
const r = recipes.find(x => x.id === 'r_zoey_chicken_split');
assert.equal(recipes.filter(x => x.id === r.id).length, 1);
assert.equal(r.dog, true);
assert.equal(r.trial, false);
assert.equal(r.fixedBatch, true);
assert.equal(r.batches.length, 2);
const [regular, plain] = r.batches;
assert.match(regular.title, /regular/i);
assert.match(plain.title, /plain/i);
assert.equal(regular.ingredients.length, 11);
assert.equal(plain.ingredients.length, 3);
assert.equal(regular.steps.length, 7);
assert.equal(plain.steps.length, 4);
const regularText = regular.ingredients.concat(regular.steps, regular.note || '', regular.subtitle || '').join(' ');
const plainText = plain.ingredients.concat(plain.steps, plain.note || '').join(' ');
assert.match(regularText, /2 cups (?:rinsed )?DRY brown rice/i);
assert.match(regularText, /2\.5 cups plain water/i);
assert.match(regularText, /5 oz (?:raw )?carrots/i);
assert.match(regularText, /5 oz green beans/i);
assert.match(regularText, /6 oz (?:green )?peas/i);
assert.match(regularText, /8 oz (?:raw )?sweet potato/i);
assert.match(regularText, /HIGH[^.]*30 minutes/i);
assert.match(regularText, /natural[^.]*float valve drops/i);
assert.match(regularText, /no basket or trivet/i);
assert.match(regularText, /entire[^.]*rice.carrot.sweet.potato/i);
assert.match(regularText, /2(?:\.25| 1\/4) level tsp[^.]*boneless/i);
assert.match(regularText, /2 level tsp[^.]*soft[^.]*bones/i);
assert.match(regularText, /stops steaming/i);
assert.match(regularText, /165.?F/);
assert.doesNotMatch(regularText, /36 oz|5\.3 oz/);
assert.match(plainText, /14 oz[^.]*rice/i);
assert.match(plainText, /separately (?:cooked|prepared)/i);
assert.match(plainText, /4[–-]8 fl oz/);
assert.match(plainText, /165.?F/);
assert.match(plain.note, /no vegetables, liver, oysters, salmon, eggshell/);
assert.match(r.blurb, /temporary, not a permanent sole diet/);
const page = {innerHTML:'', style:{}};
const context = {RECIPES:recipes, recipeServ:{}, document:{getElementById:()=>page}, window:{scrollTo(){}}, baseServ:()=>4, scaleIngredient:x=>x};
vm.createContext(context);
vm.runInContext(html.slice(html.indexOf('function setServings('), html.indexOf('function closeRecipe(')), context);
context.openRecipe(r.id);
assert.equal((page.innerHTML.match(/class="recipe-batch"/g)||[]).length, 2);
assert.match(page.innerHTML, /Chicken &amp;|Chicken &/);
assert.match(page.innerHTML, /USDA cooling guidance/);
assert.doesNotMatch(page.innerHTML, /fewer servings|more servings|placeholder card/);
context.setServings(r.id, 1);
assert.deepEqual(context.recipeServ, {});
assert.equal(context.recipeBatchesHtml({}), '');
assert.match(context.recipeBatchesHtml({batches:[{title:'<unsafe>',ingredients:[],steps:[]}]}), /&lt;unsafe&gt;/);
context.openRecipe('r_zoey_onepot');
assert.match(page.innerHTML, /more servings/);
assert.doesNotMatch(page.innerHTML, /class="recipe-batch"/);
assert.match(html, /if\(!r\|\|r\.dog\) return 0/); // No grocery writes for dog recipes.
for (const match of html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/gi)) new vm.Script(match[1]);
console.log('Zoey recipe grouping, quantities, fixed servings, legacy renderer and inline syntax passed.');
