"use strict";
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const root = path.join(__dirname, '..');
const data = fs.readFileSync(path.join(root, 'data.js'), 'utf8');
const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const recipes = vm.runInNewContext(data.slice(data.indexOf('const RECIPES = ['), data.indexOf('// 💰 FINANCE')) + '\nRECIPES');
const r = recipes.find(x => x.id === 'r_zoey_chicken_split');
assert.equal(recipes.filter(x => x.id === r.id).length, 1);
assert.equal(r.dog, true);
assert.equal(r.trial, false);
assert.equal(r.fixedBatch, true);
assert.equal(r.batches.length, 2);
assert.equal(r.batches[0].ingredients.length, 3);
assert.equal(r.batches[0].steps.length, 9);
assert.equal(r.batches[1].steps.length, 10);
assert.match(r.batches[0].note, /no vegetables, liver, oysters, salmon, eggshell/);
assert.match(r.batches[1].ingredients.join(' '), /2 1\/4 LEVEL tsp.*OR 2 LEVEL tsp/);
assert.match(r.blurb, /temporary, not a permanent sole diet/);
const page = {innerHTML:'', style:{}};
const context = {RECIPES:recipes, recipeServ:{}, document:{getElementById:()=>page}, window:{scrollTo(){}}, baseServ:()=>4, scaleIngredient:x=>x};
vm.createContext(context);
vm.runInContext(html.slice(html.indexOf('function setServings('), html.indexOf('function closeRecipe(')), context);
context.openRecipe(r.id);
assert.equal((page.innerHTML.match(/class="recipe-batch"/g)||[]).length, 2);
assert.match(page.innerHTML, /Chicken &amp;|Chicken &/);
assert.match(page.innerHTML, /USDA cooling guidance/);
assert.doesNotMatch(page.innerHTML, /fewer servings|more servings|placeholder card/);
context.setServings(r.id, 1);
assert.deepEqual(context.recipeServ, {});
assert.equal(context.recipeBatchesHtml({}), '');
assert.match(context.recipeBatchesHtml({batches:[{title:'<unsafe>',ingredients:[],steps:[]}]}), /&lt;unsafe&gt;/);
context.openRecipe('r_zoey_onepot');
assert.match(page.innerHTML, /more servings/);
assert.doesNotMatch(page.innerHTML, /class="recipe-batch"/);
assert.match(html, /if\(!r\|\|r\.dog\) return 0/); // No grocery writes for dog recipes.
for (const match of html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/gi)) new vm.Script(match[1]);
console.log('Zoey recipe grouping, quantities, fixed servings, legacy renderer and inline syntax passed.');
